compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmMinimalAgeGate: 7d

npmPreapprovedPackages:
  - "@livekit/*"
  - "livekit-client"

yarnPath: .yarn/releases/yarn-4.11.0.cjs
