name: Test
on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [main]
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 22

      - uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ~/.npm
            ~/.config/yarn/global
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Yarn
        run: |
          npm install -g yarn
          yarn

      - name: Typescript
        run: yarn typescript

      - name: ESLint
        run: yarn lint

      - name: Run Tests
        run: yarn test --passWithNoTests

      - name: Validate docs
        run: yarn build-docs --treatWarningsAsErrors
